### ISSUE TITLE
Error 800 When Opening Gerber Files

### ISSUE THREAD

**Issue by reynolds087** [OfItselfSo/LineGrinder#1]
Hi, every time I try to add a gerber file that I've generated from Kicad it gives me an error message. The one I am currently trying, for instance, returns:

"Error 800 occurred when adding line 20"

In the logs, I see the following entry:

10/27/2020 13:14:19 LineGrinder.frmMain1: PickFile called
10/27/2020 13:14:25 LineGrinder.frmMain1: Preparing to open file: D:\Google Drive\Documents\Engineering\Electrical\KiCAD\Projects\CNC\Control_Board\Control_Board\Output\Gerber\Control_Board-Edge_Cuts.gm1
10/27/2020 13:14:25 LineGrinder.ctlFileManagersDisplay: GetMatchingFileManagersObject called with>D:\Google Drive\Documents\Engineering\Electrical\KiCAD\Projects\CNC\Control_Board\Control_Board\Output\Gerber\Control_Board-Edge_Cuts.gm1
10/27/2020 13:14:25 LineGrinder.frmMain1: OpenFile, found matching manager:.gm1
10/27/2020 13:14:25 LineGrinder.frmMain1: OpenGerberFile: filePathAndName=D:\Google Drive\Documents\Engineering\Electrical\KiCAD\Projects\CNC\Control_Board\Control_Board\Output\Gerber\Control_Board-Edge_Cuts.gm1
10/27/2020 13:14:25 LineGrinder.frmMain1: ReadGerberFile: Opening file >D:\Google Drive\Documents\Engineering\Electrical\KiCAD\Projects\CNC\Control_Board\Control_Board\Output\Gerber\Control_Board-Edge_Cuts.gm1<
10/27/2020 13:14:25 LineGrinder.GerberLine_FSCode: ParseFormatParameter() started
10/27/2020 13:14:25 LineGrinder.GerberLine_MOCode: ParseModeParameter() started
10/27/2020 13:14:25 LineGrinder.GerberLine_LPCode: ParseLine(LP) started
10/27/2020 13:14:25 LineGrinder.GerberLine_GCode: ParseLine(G) failed. Unknown GCode of3
10/27/2020 13:14:25 LineGrinder.GerberFile: lineStr(g), call to ParseLine returned 334 Error on line 20
10/27/2020 13:14:25 LineGrinder.frmMain1: ReadGerberFile gerberFileToPopulate.AddLine returned 800 when adding line number 20
10/27/2020 13:14:25 LineGrinder.frmMain1: line number 20 contents >G03*<
10/27/2020 13:14:25 LineGrinder.frmMain1: Error 800 occurred when adding line number 20

Please see the log file.
10/27/2020 13:14:45 LineGrinder.frmMain1: OpenGerberFile call to ReadGerberFile returned24
10/27/2020 13:14:45 LineGrinder.frmMain1: buttonOpenFile_Click call to OpenGerberorExcellonFile returned1034

**Comment by OfItselfSo** [comment]
Looking at this now. It is a problem with the G03 arc gcode command. Any chance you can send over a simple file which reproduces this error. For confidentiality you can use the contact email on the about page of the ofitselfso.com website.

**Comment by reynolds087** [comment]
Thanks for taking a look. Here is one of the files.

**Comment by OfItselfSo** [comment]
Sorry, I am not seeing the file. Did you post it here or email it? Please resend.

**Comment by reynolds087** [comment]
It's attached to the email. I'll attach it again. Let me know if it still
doesn't show up.
  Control_Board-F_Cu.gtl
<https://drive.google.com/file/d/1pbbDmjgm5JjSIYvTHdQWQkn7VCGO1rxz/view?usp=drivesdk>

**Comment by OfItselfSo** [comment]
Sorry, no email has arrived. Maybe getting caught by a spam checker on my end or yours. Can you try zipping up the file and resending.

**Comment by reynolds087** [comment]
I zipped it up, and I also added a .txt extension onto the end in case the
filter doesn't like the gtl extension for some reason.

**Comment by OfItselfSo** [comment]
I am very sorry but I am not getting your emails. What address are you sending it to? In order to avoid getting even more spam I am going to disguise it a bit but the address to send to is cynic (at) the sites name. Where the sites name is ofitselfso.com. I have checked this account and it is working and is accepting zip files as enclosures. Sorry about this hassle but I am just not getting your emails.

**Comment by OfItselfSo** [comment]
Closing this issue
