### ISSUE TITLE
File manager metric settings

### ISSUE THREAD

**Issue by alexlinno** [OfItselfSo/LineGrinder#2]
Hi, even though application units are set to Millimeters, I am under the impression that the parameters like IsoCutWidth is still in inches....is that correct?
Thanks for your efforts
BR Alex Lindeijer

**Comment by OfItselfSo** [comment]
Check the FileManagerUnits setting in the File Manager. This is what determines the units used for all parameters in the File Manager. Unfortunately the FileManagerUnits setting cannot be changed at the moment. It is set from the Application Units when the File Manager is created. That is pretty much all the Application Units setting really does - set the default units for the creation of the File Managers. 

The solution is to drop the File Manager, set your Default Application Units to Metric and then re-create it. I realise this is not the best solution. It will be fixed - the fact that the File Manager units cannot be changed is something of a historical legacy at the moment.

If I have mis-understood the problem please let me know.

**Comment by alexlinno** [comment]
Thanks you for your quick response. Removing and adding the file managers, e.g. KiCad, after I switched to metric work fine.
I'm a software developer myself and I understand how legacy code can have implications.

**Comment by OfItselfSo** [comment]
Closing this issue. The requirement to dynamically change the File Manager units has been added a future work.
