### ISSUE TITLE
Drill Holes off by aprox. 1.3mm

### ISSUE THREAD

**Issue by tkoehn1962** [OfItselfSo/LineGrinder#4]
I am new to this and I found LibrePCB and then found LineGrinder.  I designed a simple PCB using LibrePCB and then created the G-Code with LineGrinder.  I have noticed that my drill holes are about 1.3mm off on the Y axis.  I went through the process of making sure the CNC is calibrated but the outcome still is about 1.3mm off.  

Is there a setting that I can set?

I can send you the LibrePCB Gerber files if you would like to make a FileManger template for LibrePCB.

Tony

**Comment by OfItselfSo** [comment]
Hi Tony

The drill holes should not be off by 1.3mm. For various historical reasons it is quite difficult to align the zero origin on Gerber and Drill files so this is probably a bug. 

Yes please send me the LibrePCB Gerber files. I will make a FileManager for LibrePCB and also figure out what is going wrong. You can find my email address on the About page of the website. https://www.ofitselfso.com/about.php

**Comment by OfItselfSo** [comment]
This has now confirmed to have been resolved via personal communication. The fix:
a) Download LineGrinder v03.07 (at minimum)
b) Watch the newly released video on "Aligning PCB Sides" [https://www.youtube.com/watch?v=m-DUPuRAlnc](https://www.youtube.com/watch?v=m-DUPuRAlnc)
